auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
common:
  path: /loki
  storage:
    filesystem:
      directory: /loki
  replication_factor: 1
table_manager:
  retention_deletes_enabled: true
  retention_period: 7d
